/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JtextImagen;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Ovejo
 */
public class ImagenPropiedadesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImagenPropiedadesPanel
     */
    public ImagenPropiedadesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldRuta = new javax.swing.JTextField();
        jButtonRuta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMargenSuperior = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMargenIzquierdo = new javax.swing.JTextField();

        jLabel1.setText("Ruta de la imagen:");

        jTextFieldRuta.setEditable(false);

        jButtonRuta.setText("...");
        jButtonRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRutaActionPerformed(evt);
            }
        });

        jLabel2.setText("Margen izquierdo: ");

        jTextFieldMargenSuperior.setText("0");
        jTextFieldMargenSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMargenSuperiorActionPerformed(evt);
            }
        });

        jLabel3.setText("Margen auperior:");

        jTextFieldMargenIzquierdo.setText("0");
        jTextFieldMargenIzquierdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMargenIzquierdoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMargenSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMargenIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldRuta))
                    .addComponent(jButtonRuta)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMargenSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMargenIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRutaActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        
        if (resultado == JFileChooser.APPROVE_OPTION) {
        
            File file = fileChooser.getSelectedFile();
            jTextFieldRuta.setText(file.getAbsolutePath());
        }
        
    }//GEN-LAST:event_jButtonRutaActionPerformed

    private void jTextFieldMargenSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMargenSuperiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMargenSuperiorActionPerformed

    private void jTextFieldMargenIzquierdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMargenIzquierdoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMargenIzquierdoActionPerformed

    public ImagenPropiedades getSelectedValue() {
    
       File f = new File(jTextFieldRuta.getText());
       int msuperior = Integer.parseInt(jTextFieldMargenSuperior.getText());
       int mizq = Integer.parseInt(jTextFieldMargenIzquierdo.getText());
       
       return new ImagenPropiedades(f, msuperior, mizq);
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldMargenIzquierdo;
    private javax.swing.JTextField jTextFieldMargenSuperior;
    private javax.swing.JTextField jTextFieldRuta;
    // End of variables declaration//GEN-END:variables
}
